#ifndef NDEBUG // DO NOT INCLUDE IN RELEASE BUILDS

#include "dismantleFix.h"

#include <boost/tokenizer.hpp>
#include <boost/assign.hpp>

namespace UT
{
  boost::unordered_map< std::string , std::string> DismantleFix::_fixTags
    = boost::assign::map_list_of 
    ( "1", "Account")
    ( "2", "AdvId")
    ( "3", "AdvRefID")
    ( "4", "AdvSide")
    ( "5", "AdvTransType")
    ( "6", "AvgPx")
    ( "7", "BeginSeqNo")
    ( "8", "BeginString")
    ( "9", "BodyLength")
    ( "10", "CheckSum")
    ( "11", "ClOrdID")
    ( "12", "Commission")
    ( "13", "CommType")
    ( "14", "CumQty")
    ( "15", "Currency")
    ( "16", "EndSeqNo")
    ( "17", "ExecID")
    ( "18", "ExecInst")
    ( "19", "ExecRefID")
    ( "20", "ExecTransType")
    ( "21", "HandlInst")
    ( "22", "IDSource")
    ( "23", "IOIid")
    ( "24", "IOIOthSvc")
    ( "25", "IOIQltyInd")
    ( "26", "IOIRefID")
    ( "27", "IOIShares")
    ( "28", "IOITransType")
    ( "29", "LastCapacity")
    ( "30", "LastMkt")
    ( "31", "LastPx")
    ( "32", "LastShares")
    ( "33", "LinesOfText")
    ( "34", "MsgSeqNum")
    ( "35", "MsgType")
    ( "36", "NewSeqNo")
    ( "37", "OrderID")
    ( "38", "OrderQty")
    ( "39", "OrdStatus")
    ( "40", "OrdType")
    ( "41", "OrigClOrdID")
    ( "42", "OrigTime")
    ( "43", "PossDupFlag")
    ( "44", "Price")
    ( "45", "RefSeqNum")
    ( "46", "RelatdSym")
    ( "47", "Rule80A")
    ( "48", "SecurityID")
    ( "49", "SenderCompID")
    ( "50", "SenderSubID")
    ( "51", "SendingDate")
    ( "52", "SendingTime")
    ( "53", "Shares")
    ( "54", "Side")
    ( "55", "Symbol")
    ( "56", "TargetCompID")
    ( "57", "TargetSubID")
    ( "58", "Text")
    ( "59", "TimeInForce")
    ( "60", "TransactTime")
    ( "61", "Urgency")
    ( "62", "ValidUntilTime")
    ( "63", "SettlmntTyp")
    ( "64", "FutSettDate")
    ( "65", "SymbolSfx")
    ( "66", "ListID")
    ( "67", "ListSeqNo")
    ( "68", "TotNoOrders")
    ( "69", "ListExecInst")
    ( "70", "AllocID")
    ( "71", "AllocTransType")
    ( "72", "RefAllocID")
    ( "73", "NoOrders")
    ( "74", "AvgPrxPrecision")
    ( "75", "TradeDate")
    ( "76", "ExecBroker")
    ( "77", "OpenClose")
    ( "78", "NoAllocs")
    ( "79", "AllocAccount")
    ( "80", "AllocShares")
    ( "81", "ProcessCode")
    ( "82", "NoRpts")
    ( "83", "RptSeq")
    ( "84", "CxlQty")
    ( "85", "NoDlvyInst")
    ( "86", "DlvyInst")
    ( "87", "AllocStatus")
    ( "88", "AllocRejCode")
    ( "89", "Signature")
    ( "90", "SecureDataLen")
    ( "91", "SecureData")
    ( "92", "BrokerOfCredit")
    ( "93", "SignatureLength")
    ( "94", "EmailType")
    ( "95", "RawDataLength")
    ( "96", "RawData")
    ( "97", "PossResend")
    ( "98", "EncryptMethod")
    ( "99", "StopPx")
    ( "100", "ExDestination")
    ( "102", "CxlRejReason")
    ( "103", "OrdRejReason")
    ( "104", "IOIQualifier")
    ( "105", "WaveNo")
    ( "106", "Issuer")
    ( "107", "SecurityDesc")
    ( "108", "HeartBtInt")
    ( "109", "ClientID")
    ( "110", "MinQty")
    ( "111", "MaxFloor")
    ( "112", "TestReqID")
    ( "113", "ReportToExch")
    ( "114", "LocateReqd")
    ( "115", "OnBehalfOfCompID")
    ( "116", "OnBehalfOfSubID")
    ( "117", "QuoteID")
    ( "118", "NetMoney")
    ( "119", "SettlCurrAmt")
    ( "120", "SettlCurrency")
    ( "121", "ForexReq")
    ( "122", "OrigSendingTime")
    ( "123", "GapFillFlag")
    ( "124", "NoExecs")
    ( "125", "CxlType")
    ( "126", "ExpireTime")
    ( "127", "DKReason")
    ( "128", "DeliverToCompID")
    ( "129", "DeliverToSubID")
    ( "130", "IOINaturalFlag")
    ( "131", "QuoteReqID")
    ( "132", "BidPx")
    ( "133", "OfferPx")
    ( "134", "BidSize")
    ( "135", "OfferSize")
    ( "136", "NoMiscFees")
    ( "137", "MiscFeeAmt")
    ( "138", "MiscFeeCurr")
    ( "139", "MiscFeeType")
    ( "140", "PrevClosePx")
    ( "141", "ResetSeqNumFlag")
    ( "142", "SenderLocationID")
    ( "143", "TargetLocationID")
    ( "144", "OnBehalfOfLocationID")
    ( "145", "DeliverToLocationID")
    ( "146", "NoRelatedSym")
    ( "147", "Subject")
    ( "148", "Headline")
    ( "149", "URLLink")
    ( "150", "ExecType")
    ( "151", "LeavesQty")
    ( "152", "CashOrderQty")
    ( "153", "AllocAvgPx")
    ( "154", "AllocNetMoney")
    ( "155", "SettlCurrFxRate")
    ( "156", "SettlCurrFxRateCalc")
    ( "157", "NumDaysInterest")
    ( "158", "AccruedInterestRate")
    ( "159", "AccruedInterestAmt")
    ( "160", "SettlInstMode")
    ( "161", "AllocText")
    ( "162", "SettlInstID")
    ( "163", "SettlInstTransType")
    ( "164", "EmailThreadID")
    ( "165", "SettlInstSource")
    ( "166", "SettlLocation")
    ( "167", "SecurityType")
    ( "168", "EffectiveTime")
    ( "169", "StandInstDbType")
    ( "170", "StandInstDbName")
    ( "171", "StandInstDbID")
    ( "172", "SettlDeliveryType")
    ( "173", "SettlDepositoryCode")
    ( "174", "SettlBrkrCode")
    ( "175", "SettlInstCode")
    ( "176", "SecuritySettlAgentName")
    ( "177", "SecuritySettlAgentCode")
    ( "178", "SecuritySettlAgentAcctNum")
    ( "179", "SecuritySettlAgentAcctName")
    ( "180", "SecuritySettlAgentContactName")
    ( "181", "SecuritySettlAgentContactPhone")
    ( "182", "CashSettlAgentName")
    ( "183", "CashSettlAgentCode")
    ( "184", "CashSettlAgentAcctNum")
    ( "185", "CashSettlAgentAcctName")
    ( "186", "CashSettlAgentContactName")
    ( "187", "CashSettlAgentContactPhone")
    ( "188", "BidSpotRate")
    ( "189", "BidForwardPoints")
    ( "190", "OfferSpotRate")
    ( "191", "OfferForwardPoints")
    ( "192", "OrderQty2")
    ( "193", "FutSettDate2")
    ( "194", "LastSpotRate")
    ( "195", "LastForwardPoints")
    ( "196", "AllocLinkID")
    ( "197", "AllocLinkType")
    ( "198", "SecondaryOrderID")
    ( "199", "NoIOIQualifiers")
    ( "200", "MaturityMonthYear")
    ( "201", "PutOrCall")
    ( "202", "StrikePrice")
    ( "203", "CoveredOrUncovered")
    ( "204", "CustomerOrFirm")
    ( "205", "MaturityDay")
    ( "206", "OptAttribute")
    ( "207", "SecurityExchange")
    ( "208", "NotifyBrokerOfCredit")
    ( "209", "AllocHandlInst")
    ( "210", "MaxShow")
    ( "211", "PegDifference")
    ( "212", "XmlDataLen")
    ( "213", "XmlData")
    ( "214", "SettlInstRefID")
    ( "215", "NoRoutingIDs")
    ( "216", "RoutingType")
    ( "217", "RoutingID")
    ( "218", "SpreadToBenchmark")
    ( "219", "Benchmark")
    ( "223", "CouponRate")
    ( "228", "Factor")
    ( "231", "ContractMultiplier")
    ( "262", "MDReqID")
    ( "263", "SubscriptionRequestType")
    ( "264", "MarketDepth")
    ( "265", "MDUpdateType")
    ( "266", "AggregatedBook")
    ( "267", "NoMDEntryTypes")
    ( "268", "NoMDEntries")
    ( "269", "MDEntryType")
    ( "270", "MDEntryPx")
    ( "271", "MDEntrySize")
    ( "272", "MDEntryDate")
    ( "273", "MDEntryTime")
    ( "274", "TickDirection")
    ( "275", "MDMkt")
    ( "276", "QuoteCondition")
    ( "277", "TradeCondition")
    ( "278", "MDEntryID")
    ( "279", "MDUpdateAction")
    ( "280", "MDEntryRefID")
    ( "281", "MDReqRejReason")
    ( "282", "MDEntryOriginator")
    ( "283", "LocationID")
    ( "284", "DeskID")
    ( "285", "DeleteReason")
    ( "286", "OpenCloseSettleFlag")
    ( "287", "SellerDays")
    ( "288", "MDEntryBuyer")
    ( "289", "MDEntrySeller")
    ( "290", "MDEntryPositionNo")
    ( "291", "FinancialStatus")
    ( "292", "CorporateAction")
    ( "293", "DefBidSize")
    ( "294", "DefOfferSize")
    ( "295", "NoQuoteEntries")
    ( "296", "NoQuoteSets")
    ( "297", "QuoteAckStatus")
    ( "298", "QuoteCancelType")
    ( "299", "QuoteEntryID")
    ( "300", "QuoteRejectReason")
    ( "301", "QuoteResponseLevel")
    ( "302", "QuoteSetID")
    ( "303", "QuoteRequestType")
    ( "304", "TotQuoteEntries")
    ( "305", "UnderlyingIDSource")
    ( "306", "UnderlyingIssuer")
    ( "307", "UnderlyingSecurityDesc")
    ( "308", "UnderlyingSecurityExchange")
    ( "309", "UnderlyingSecurityID")
    ( "310", "UnderlyingSecurityType")
    ( "311", "UnderlyingSymbol")
    ( "312", "UnderlyingSymbolSfx")
    ( "313", "UnderlyingMaturityMonthYear")
    ( "314", "UnderlyingMaturityDay")
    ( "315", "UnderlyingPutOrCall")
    ( "316", "UnderlyingStrikePrice")
    ( "317", "UnderlyingOptAttribute")
    ( "318", "UnderlyingCurrency")
    ( "319", "RatioQty")
    ( "320", "SecurityReqID")
    ( "321", "SecurityRequestType")
    ( "322", "SecurityResponseID")
    ( "323", "SecurityResponseType")
    ( "324", "SecurityStatusReqID")
    ( "325", "UnsolicitedIndicator")
    ( "326", "SecurityTradingStatus")
    ( "327", "HaltReason")
    ( "328", "InViewOfCommon")
    ( "329", "DueToRelated")
    ( "330", "BuyVolume")
    ( "331", "SellVolume")
    ( "332", "HighPx")
    ( "333", "LowPx")
    ( "334", "Adjustment")
    ( "335", "TradSesReqID")
    ( "336", "TradingSessionID")
    ( "337", "ContraTrader")
    ( "338", "TradSesMethod")
    ( "339", "TradSesMode")
    ( "340", "TradSesStatus")
    ( "341", "TradSesStartTime")
    ( "342", "TradSesOpenTime")
    ( "343", "TradSesPreCloseTime")
    ( "344", "TradSesCloseTime")
    ( "345", "TradSesEndTime")
    ( "346", "NumberOfOrders")
    ( "347", "MessageEncoding")
    ( "348", "EncodedIssuerLen")
    ( "349", "EncodedIssuer")
    ( "350", "EncodedSecurityDescLen")
    ( "351", "EncodedSecurityDesc")
    ( "352", "EncodedListExecInstLen")
    ( "353", "EncodedListExecInst")
    ( "354", "EncodedTextLen")
    ( "355", "EncodedText")
    ( "356", "EncodedSubjectLen")
    ( "357", "EncodedSubject")
    ( "358", "EncodedHeadlineLen")
    ( "359", "EncodedHeadline")
    ( "360", "EncodedAllocTextLen")
    ( "361", "EncodedAllocText")
    ( "362", "EncodedUnderlyingIssuerLen")
    ( "363", "EncodedUnderlyingIssuer")
    ( "364", "EncodedUnderlyingSecurityDescLen")
    ( "365", "EncodedUnderlyingSecurityDesc")
    ( "366", "AllocPrice")
    ( "367", "QuoteSetValidUntilTime")
    ( "368", "QuoteEntryRejectReason")
    ( "369", "LastMsgSeqNumProcessed")
    ( "370", "OnBehalfOfSendingTime")
    ( "371", "RefTagID")
    ( "372", "RefMsgType")
    ( "373", "SessionRejectReason")
    ( "374", "BidRequestTransType")
    ( "375", "ContraBroker")
    ( "376", "ComplianceID")
    ( "377", "SolicitedFlag")
    ( "378", "ExecRestatementReason")
    ( "379", "BusinessRejectRefID")
    ( "380", "BusinessRejectReason")
    ( "381", "GrossTradeAmt")
    ( "382", "NoContraBrokers")
    ( "383", "MaxMessageSize")
    ( "384", "NoMsgTypes")
    ( "385", "MsgDirection")
    ( "386", "NoTradingSessions")
    ( "387", "TotalVolumeTraded")
    ( "388", "DiscretionInst")
    ( "389", "DiscretionOffset")
    ( "390", "BidID")
    ( "391", "ClientBidID")
    ( "392", "ListName")
    ( "393", "TotalNumSecurities")
    ( "394", "BidType")
    ( "395", "NumTickets")
    ( "396", "SideValue1")
    ( "397", "SideValue2")
    ( "398", "NoBidDescriptors")
    ( "399", "BidDescriptorType")
    ( "400", "BidDescriptor")
    ( "401", "SideValueInd")
    ( "402", "LiquidityPctLow")
    ( "403", "LiquidityPctHigh")
    ( "404", "LiquidityValue")
    ( "405", "EFPTrackingError")
    ( "406", "FairValue")
    ( "407", "OutsideIndexPct")
    ( "408", "ValueOfFutures")
    ( "409", "LiquidityIndType")
    ( "410", "WtAverageLiquidity")
    ( "411", "ExchangeForPhysical")
    ( "412", "OutMainCntryUIndex")
    ( "413", "CrossPercent")
    ( "414", "ProgRptReqs")
    ( "415", "ProgPeriodInterval")
    ( "416", "IncTaxInd")
    ( "417", "NumBidders")
    ( "418", "TradeType")
    ( "419", "BasisPxType")
    ( "420", "NoBidComponents")
    ( "421", "Country")
    ( "422", "TotNoStrikes")
    ( "423", "PriceType")
    ( "424", "DayOrderQty")
    ( "425", "DayCumQty")
    ( "426", "DayAvgPx")
    ( "427", "GTBookingInst")
    ( "428", "NoStrikes")
    ( "429", "ListStatusType")
    ( "430", "NetGrossInd")
    ( "431", "ListOrderStatus")
    ( "432", "ExpireDate")
    ( "433", "ListExecInstType")
    ( "434", "CxlRejResponseTo")
    ( "435", "UnderlyingCouponRate")
    ( "436", "UnderlyingContractMultiplier")
    ( "437", "ContraTradeQty")
    ( "438", "ContraTradeTime")
    ( "439", "ClearingFirm")
    ( "440", "ClearingAccount")
    ( "441", "LiquidityNumSecurities")
    ( "442", "MultiLegReportingType")
    ( "443", "StrikeTime")
    ( "444", "ListStatusText")
    ( "445", "EncodedListStatusTextLen")
    ( "446", "EncodedListStatusText")
    ( "5001", "AlgorithmType")
    ( "5002", "ParentOrderId")
    ( "5003", "UserId")
    ( "5004", "DeltaQty")
    ( "5005", "DerivativeSymbolType")
    ( "5006", "ID6A7A")
    ( "5007", "TradeId")
    ( "5008", "TransactionCode")
    ( "5010", "SettGroup")
    ( "5011", "ISINCode")
    ( "5012", "PhysicalQty")
    ( "5013", "DmatNSDLQty")
    ( "5014", "DmatCDSQty")
    ( "5015", "TypeOfDeal")
    ( "5016", "SettlementNo")
    ( "5017", "DayFlag")
    ( "5018", "ReplyCode")
    ( "5019", "ExerciseQty")
    ( "5020", "ScripCode")
    ( "5021", "ExchCreateTime")
    ( "5022", "ExchModifyTime")
    ( "5023", "ProductType")
    ( "5024", "OriginalOrderType")
    ( "5025", "SquareOff")
    ( "5027", "SeqNum")
    ( "864", "NoEvents")
    ( "865", "EventType")
    ( "866", "EventDate")
    ( "10442", "ExpectedFillType")
    ( "10455", "SecurityAltID")
    ( "16309", "ExchContractSymbol")
    ( "16451", "PriceDisplayType")
    ( "16452", "TickSize")
    ( "16454", "PointValue")
    ( "16456", "NumTickTblEntries")
    ( "16457", "NumTicks")
    ( "16458", "MaxPrice")
    ( "16461", "LotSize")
    ( "16552", "ExchTickSize")
    ( "16554", "ExchPointValue")
    ( "16899", "MarginExcess")
    ( "17000", "RequestTickTable")
    ( "18000", "ForceLogout")
    ( "18203", "ExchangeGateway")
    ( "18206", "NoGateways")
    ( "18207", "TTSecurityAlias")
    ( "21020", "PresentValue")
    ( "22000", "TransactionId") ;

  boost::unordered_map< std::string , std::string> DismantleFix::_fixTagsDesc
    = boost::assign::map_list_of 
    ( "4-B", "Buy")
    ( "4-S", "Sell")
    ( "4-X", "Cross")
    ( "4-T", "Trade")
    ( "5-N", "New")
    ( "5-C", "Cancel")
    ( "5-R", "Replace")
    ( "13-1", "per share")
    ( "13-2", "percentage")
    ( "13-3", "absolute")
    ( "18-1", "Not held")
    ( "18-2", "Work")
    ( "18-3", "Go along")
    ( "18-4", "Over the day")
    ( "18-5", "Held")
    ( "18-6", "Participate don't initiate")
    ( "18-7", "Strict scale")
    ( "18-8", "Try to scale")
    ( "18-9", "Stay on bidside")
    ( "18-0", "Stay on offerside")
    ( "18-A", "No cross (cross is forbidden)")
    ( "18-B", "OK to cross")
    ( "18-C", "Call first")
    ( "18-D", "Percent of volume '(indicates that the sender does not want to"
              " be all of the volume on the floor vs. a specific percentage)'")
    ( "18-E", "Do not increase - DNI")
    ( "18-F", "Do not reduce - DNR")
    ( "18-G", "All or none - AON")
    ( "18-I", "Institutions only")
    ( "18-L", "Last peg (last sale)")
    ( "18-M", "Mid-price peg (midprice of inside quote)")
    ( "18-N", "Non-negotiable")
    ( "18-O", "Opening peg")
    ( "18-P", "Market peg")
    ( "18-R", "Primary peg (primary market - buy at bid/sell at offer)")
    ( "18-S", "Suspend")
    ( "18-T", "Fixed Peg to Local best bid or offer at time of order")
    ( "18-U", "Customer Display Instruction (Rule11Ac1-1/4)")
    ( "18-V", "Netting (for Forex)")
    ( "18-W", "Peg to VWAP")
    ( "20-0", "New")
    ( "20-1", "Cancel")
    ( "20-2", "Correct")
    ( "20-3", "Status")
    ( "21-1", "Automated execution order, private, no Broker intervention")
    ( "21-2", "Automated execution order, public, Broker intervention OK")
    ( "21-3", "Manual order, best execution")
    ( "22-1", "CUSIP")
    ( "22-2", "SEDOL")
    ( "22-3", "QUIK")
    ( "22-4", "ISIN number")
    ( "22-5", "RIC code")
    ( "22-6", "ISO Currency <15> Code")
    ( "22-7", "ISO Country <421> Code")
    ( "22-8", "Exchange Symbol <55>")
    ( "22-9", "Consolidated Tape Association (CTA) Symbol <55> (SIAC CTS/CQS "
              "line format)")
    ( "25-L", "Low")
    ( "25-M", "Medium")
    ( "25-H", "High")
    ( "27-0", "1000000000")
    ( "27-S", "Small")
    ( "27-M", "Medium")
    ( "27-L", "Large")
    ( "28-N", "New")
    ( "28-C", "Cancel")
    ( "28-R", "Replace")
    ( "29-1", "Agent")
    ( "29-2", "Cross as agent")
    ( "29-3", "Cross as principal")
    ( "29-4", "Principal")
    ( "35-0", "Heartbeat")
    ( "35-1", "Test Request")
    ( "35-2", "Resend Request")
    ( "35-3", "Reject")
    ( "35-4", "Sequence Reset")
    ( "35-5", "Logout")
    ( "35-6", "Indication of Interest")
    ( "35-7", "Advertisement")
    ( "35-8", "Execution Report")
    ( "35-9", "Order Cancel Reject")
    ( "35-A", "Logon")
    ( "35-B", "News")
    ( "35-C", "Email")
    ( "35-D", "Order - Single")
    ( "35-E", "Order - List")
    ( "35-F", "Order Cancel Request")
    ( "35-G", "Order Cancel/Replace Request")
    ( "35-H", "Order Status Request")
    ( "35-J", "Allocation")
    ( "35-K", "List Cancel Request")
    ( "35-L", "List Execute")
    ( "35-M", "List Status Request")
    ( "35-N", "List Status")
    ( "35-P", "Allocation ACK")
    ( "35-Q", "Don't Know Trade")
    ( "35-R", "Quote Request")
    ( "35-S", "Quote")
    ( "35-T", "Settlement Instructions")
    ( "35-V", "Market Data Request")
    ( "35-W", "Market Data-Snapshot/Full Refresh")
    ( "35-X", "Market Data-Incremental Refresh")
    ( "35-Y", "Market Data Request Reject")
    ( "35-Z", "Quote Cancel")
    ( "35-a", "Quote Status Request")
    ( "35-b", "Quote Acknowledgement")
    ( "35-c", "Security Definition Request")
    ( "35-d", "Security Definition")
    ( "35-e", "Security Status Request")
    ( "35-f", "Security Status")
    ( "35-g", "Trading Session Status Request")
    ( "35-h", "Trading Session Status")
    ( "35-i", "Mass Quote")
    ( "35-j", "Business Message Reject")
    ( "35-k", "Bid Request")
    ( "35-l", "Bid Response")
    ( "35-m", "List Strike Price")
    ( "39-0", "New")
    ( "39-1", "Partially filled")
    ( "39-2", "Filled")
    ( "39-3", "Done for day")
    ( "39-4", "Canceled")
    ( "39-5", "Replaced")
    ( "39-6", "Pending Cancel")
    ( "39-7", "Stopped")
    ( "39-8", "Rejected")
    ( "39-9", "Suspended")
    ( "39-A", "Pending New")
    ( "39-B", "Calculated")
    ( "39-C", "Expired")
    ( "39-D", "Accepted for bidding")
    ( "39-E", "Pending Replace")
    ( "40-1", "Market")
    ( "40-2", "Limit")
    ( "40-3", "Stop")
    ( "40-4", "Stop limit")
    ( "40-5", "Market on close")
    ( "40-6", "With or without")
    ( "40-7", "Limit or better")
    ( "40-8", "Limit with or without")
    ( "40-9", "On basis")
    ( "40-A", "On close")
    ( "40-B", "Limit on close")
    ( "40-C", "Forex - Market")
    ( "40-D", "Previously quoted")
    ( "40-E", "Previously indicated")
    ( "40-F", "Forex - Limit")
    ( "40-G", "Forex - Swap")
    ( "40-H", "Forex - Previously Quoted")
    ( "40-I", "Funari (Limit Day Order with unexecuted portion handled as "
              "Market On Close. e.g. Japan)")
    ( "40-P", "Pegged")
    ( "43-Y", "Possible duplicate")
    ( "43-N", "Original transmission")
    ( "47-A", "Agency single order")
    ( "47-B", "Short exempt transaction (refer to A type)")
    ( "47-C", "Program Order, non-index arb, for Member firm/org")
    ( "47-D", "Program Order, index arb, for Member firm/org")
    ( "47-E", "Registered Equity Market Maker trades")
    ( "47-F", "Short exempt transaction (refer to W type)")
    ( "47-H", "Short exempt transaction (refer to I type)")
    ( "47-I", "Individual Investor, single order")
    ( "47-J", "Program Order, index arb, for individual customer")
    ( "47-K", "Program Order, non-index arb, for individual customer")
    ( "47-L", "Short exempt transaction for member competing market-maker "
              "affiliated with the firm clearing the trade (refer to P and")
    ( "47-M", "Program Order, index arb, for other member")
    ( "47-N", "Program Order, non-index arb, for other member")
    ( "47-O", "Competing dealer trades")
    ( "47-P", "Principal")
    ( "47-R", "Competing dealer trades")
    ( "47-S", "Specialist trades")
    ( "47-T", "Competing dealer trades")
    ( "47-U", "Program Order, index arb, for other agency")
    ( "47-W", "All other orders as agent for other member")
    ( "47-X", "Short exempt transaction for member competing market-maker not "
              "affiliated with the firm clearing the trade (refer to W")
    ( "47-Y", "Program Order, non-index arb, for other agency")
    ( "47-Z", "Short exempt transaction for non-member competing market-maker "
              "(refer to A and R types)")
    ( "54-1", "Buy")
    ( "54-2", "Sell")
    ( "54-3", "Buy minus")
    ( "54-4", "Sell plus")
    ( "54-5", "Sell short")
    ( "54-6", "Sell short exempt")
    ( "54-7", "Undisclosed (valid for IOI and List Order messages only)")
    ( "54-8", "Cross (orders where counterparty is an exchange, valid for all "
              "messages except IOIs)")
    ( "54-9", "Cross short")
    ( "59-0", "Day")
    ( "59-1", "Good Till Cancel (GTC)")
    ( "59-2", "At the Opening (OPG)")
    ( "59-3", "Immediate or Cancel (IOC)")
    ( "59-4", "Fill or Kill (FOK)")
    ( "59-5", "Good Till Crossing (GTX)")
    ( "59-6", "Good Till Date")
    ( "61-0", "Normal")
    ( "61-1", "Flash")
    ( "61-2", "Background")
    ( "63-0", "Regular")
    ( "63-1", "Cash")
    ( "63-2", "Next Day")
    ( "63-3", "T+2")
    ( "63-4", "T+3")
    ( "63-5", "T+4")
    ( "63-6", "Future")
    ( "63-7", "When Issued")
    ( "63-8", "Sellers Option")
    ( "63-9", "T+ 5")
    ( "71-0", "New")
    ( "71-1", "Replace")
    ( "71-2", "Cancel")
    ( "71-3", "Preliminary (without MiscFees and NetMoney)")
    ( "71-4", "Calculated (includes MiscFees and NetMoney)")
    ( "71-5", "Calculated without Preliminary (sent unsolicited by broker, "
              "includes MiscFees and NetMoney)")
    ( "81-0", "regular")
    ( "81-1", "soft dollar")
    ( "81-2", "step-in")
    ( "81-3", "step-out")
    ( "81-4", "soft-dollar step-in")
    ( "81-5", "soft-dollar step-out")
    ( "81-6", "plan sponsor")
    ( "87-0", "accepted (successfully processed)")
    ( "87-1", "rejected")
    ( "87-2", "partial accept")
    ( "87-3", "received (received, not yet processed)")
    ( "88-0", "unknown account(s)")
    ( "88-1", "incorrect quantity")
    ( "88-2", "incorrect average price")
    ( "88-3", "unknown executing broker mnemonic")
    ( "88-4", "commission difference")
    ( "88-5", "unknown OrderID")
    ( "88-6", "unknown ListID")
    ( "88-7", "other")
    ( "94-0", "New")
    ( "94-1", "Reply")
    ( "94-2", "Admin Reply")
    ( "98-0", "None / other")
    ( "98-1", "PKCS (proprietary)")
    ( "98-2", "DES (ECB mode)")
    ( "98-3", "PKCS/DES (proprietary)")
    ( "98-4", "PGP/DES (defunct)")
    ( "98-5", "PGP/DES-MD5 (see app note on FIX web site)")
    ( "98-6", "PEM/DES-MD5 (see app note on FIX web site)")
    ( "102-0", "Too late to cancel")
    ( "102-1", "Unknown order")
    ( "102-2", "Broker Option")
    ( "102-3", "Order already in Pending Cancel or Pending Replace status")
    ( "103-0", "Broker option")
    ( "103-1", "Unknown symbol")
    ( "103-2", "Exchange closed")
    ( "103-3", "Order exceeds limit")
    ( "103-4", "Too late to enter")
    ( "103-5", "Unknown Order")
    ( "103-6", "Duplicate Order (e.g. dupe ClOrdID )")
    ( "103-7", "Duplicate of a verbally communicated order")
    ( "103-8", "Stale Order")
    ( "104-A", "All or none")
    ( "104-C", "At the close")
    ( "104-I", "In touch with")
    ( "104-L", "Limit")
    ( "104-M", "More behind")
    ( "104-O", "At the open")
    ( "104-P", "Taking a position")
    ( "104-Q", "At the Market (previously called Current Quote)")
    ( "104-R", "Ready to trade")
    ( "104-S", "Portfolio show-n")
    ( "104-T", "Through the day")
    ( "104-V", "Versus")
    ( "104-W", "Indication - Working away")
    ( "104-X", "Crossing opportunity")
    ( "104-Y", "At the Midpoint")
    ( "104-Z", "Pre-open")
    ( "113-Y", "Indicates that party receiving message must report trade")
    ( "113-N", "Indicates that party sending message will report trade")
    ( "114-Y", "Indicates the broker is responsible for locating the stock")
    ( "114-N", "Indicates the broker is not required to locate")
    ( "121-Y", "Execute Forex after security trade")
    ( "121-N", "Do not execute Forex after security trade")
    ( "123-Y", "Gap Fill message, MsgSeqNum")
    ( "123-N", "Sequence Reset")
    ( "127-A", "Unknown symbol")
    ( "127-B", "Wrong side")
    ( "127-C", "Quantity exceeds order")
    ( "127-D", "No matching order")
    ( "127-E", "Price exceeds limit")
    ( "127-Z", "Other")
    ( "130-Y", "Natural")
    ( "130-N", "Not natural")
    ( "139-1", "Regulatory (e.g. SEC)")
    ( "139-2", "Tax")
    ( "139-3", "Local Commission")
    ( "139-4", "Exchange Fees")
    ( "139-5", "Stamp")
    ( "139-6", "Levy")
    ( "139-7", "Other")
    ( "139-8", "Markup")
    ( "139-9", "Consumption Tax")
    ( "141-Y", "Yes, reset sequence numbers")
    ( "141-N", "No")
    ( "150-0", "New")
    ( "150-1", "Partial fill")
    ( "150-2", "Fill")
    ( "150-3", "Done for day")
    ( "150-4", "Canceled")
    ( "150-5", "Replace")
    ( "150-6", "Pending Cancel")
    ( "150-7", "Stopped")
    ( "150-8", "Rejected")
    ( "150-9", "Suspended")
    ( "150-A", "Pending New")
    ( "150-B", "Calculated")
    ( "150-C", "Expired")
    ( "150-D", "Restated")
    ( "150-E", "Pending Replace")
    ( "150-T", "Triggered")
    ( "160-0", "Default")
    ( "160-1", "Standing Instructions Provided")
    ( "160-2", "Specific Allocation")
    ( "160-3", "Specific Allocation")
    ( "163-N", "New")
    ( "163-C", "Cancel")
    ( "163-R", "Replace")
    ( "165-1", "Broker's Instructions")
    ( "165-2", "Institution's Instructions")
    ( "166-CED", "CEDEL")
    ( "166-DTC", "Depository Trust Company")
    ( "166-EUR", "Euroclear")
    ( "166-FED", "Federal Book Entry")
    ( "166-PNY", "Physical")
    ( "166-PTC", "Participant Trust Company")
    ( "167-BA", "Bankers Acceptance")
    ( "167-CB", "Convertible Bond (Note not part of ISITC spec)")
    ( "167-CD", "Certificate Of Deposit")
    ( "167-CMO", "Collateralize Mortgage Obligation")
    ( "167-CORP", "Corporate Bond")
    ( "167-CP", "Commercial Paper")
    ( "167-CPP", "Corporate Private Placement")
    ( "167-CS", "Common Stock")
    ( "167-FHA", "Federal Housing Authority")
    ( "167-FHL", "Federal Home Loan")
    ( "167-FN", "Federal National Mortgage Association")
    ( "167-FOR", "Foreign Exchange Contract")
    ( "167-FUT", "Future")
    ( "167-GN", "Government National Mortgage Association")
    ( "167-GOVT", "Treasuries + Agency Debenture")
    ( "167-IET", "Mortgage IOETTE")
    ( "167-MF", "Mutual Fund")
    ( "167-MIO", "Mortgage Interest Only")
    ( "167-MPO", "Mortgage Principal Only")
    ( "167-MPP", "Mortgage Private Placement")
    ( "167-MPT", "Miscellaneous Pass-Thru")
    ( "167-MUNI", "Municipal Bond")
    ( "167-NONE", "No ISITC Security Type")
    ( "167-OPT", "Option")
    ( "167-PS", "Preferred Stock")
    ( "167-RP", "Repurchase Agreement")
    ( "167-RVRP", "Reverse Repurchase Agreement")
    ( "167-SL", "Student Loan Marketing Association")
    ( "167-TD", "Time Deposit")
    ( "167-USTB", "US Treasury Bill")
    ( "167-WAR", "Warrant")
    ( "167-ZOO", "Cats, Tigers &amp; Lions (a real code: US Treasury Receipts)")
    ( "167-?", "'Wildcard' entry")
    ( "169-0", "Other")
    ( "169-1", "DTC SID")
    ( "169-2", "Thomson ALERT")
    ( "169-3", "A Global Custodian")
    ( "197-0", "F/X Netting")
    ( "197-1", "F/X Swap")
    ( "201-0", "Put")
    ( "201-1", "Call")
    ( "203-0", "Covered")
    ( "203-1", "Uncovered")
    ( "204-0", "Customer")
    ( "204-1", "Firm")
    ( "206-L", "Long (a.k.a. 'American')")
    ( "206-S", "Short (a.k.a. 'European')")
    ( "208-Y", "Details should be communicated")
    ( "208-N", "Details should not be communicated")
    ( "209-1", "Match")
    ( "209-2", "Forward")
    ( "209-3", "Forward and Match")
    ( "216-1", "Target Firm")
    ( "216-2", "Target List")
    ( "216-3", "Block Firm")
    ( "216-4", "Block List")
    ( "219-1", "CURVE")
    ( "219-2", "5-YR")
    ( "219-3", "OLD-5")
    ( "219-4", "10-YR")
    ( "219-5", "OLD-10")
    ( "219-6", "30-YR")
    ( "219-7", "OLD-30")
    ( "219-8", "3-MO-LIBOR")
    ( "219-9", "6-MO-LIBOR")
    ( "263-0", "Snapshot")
    ( "263-1", "Snapshot + Updates (Subscribe)")
    ( "263-2", "Disable previous Snapshot + Update Request (Unsubscribe)")
    ( "264-0", "Full Book")
    ( "264-1", "Top of Book")
    ( "265-0", "Full Refresh")
    ( "265-1", "Incremental Refresh")
    ( "266-Y", "one book entry per side per price")
    ( "266-N", "Multiple entries per side per price allowed")
    ( "269-0", "Bid")
    ( "269-1", "Offer")
    ( "269-2", "Trade")
    ( "269-3", "Index Value")
    ( "269-4", "Opening Price")
    ( "269-5", "Closing Price")
    ( "269-6", "Settlement Price")
    ( "269-7", "Trading Session High Price")
    ( "269-8", "Trading Session Low Price")
    ( "269-9", "Trading Session VWAP Price")
    ( "274-0", "Plus Tick")
    ( "274-1", "Zero-Plus Tick")
    ( "274-2", "Minus Tick")
    ( "274-3", "Zero-Minus Tick")
    ( "276-A", "Open / Active")
    ( "276-B", "Closed / Inactive")
    ( "276-C", "Exchange Best")
    ( "276-D", "Consolidated Best")
    ( "276-E", "Locked")
    ( "276-F", "Crossed")
    ( "276-G", "Depth")
    ( "276-H", "Fast Trading")
    ( "276-I", "Non-Firm")
    ( "277-A", "Cash (only) Market")
    ( "277-B", "Average Price")
    ( "277-C", "Cash Trade (same day clearing)")
    ( "277-D", "Next Day (only) Market")
    ( "277-E", "Opening / Reopening Trade Detail")
    ( "277-F", "Intraday Trade Detail")
    ( "277-G", "Rule 127 Trade (NYSE)")
    ( "277-H", "Rule 155 Trade (Amex)")
    ( "277-I", "Sold Last (late reporting)")
    ( "277-J", "Next Day Trade (next day clearing)")
    ( "277-K", "Opened (late report of opened trade)")
    ( "277-L", "Seller")
    ( "277-M", "Sold (out of sequence)")
    ( "277-N", "Stopped Stock (guarantee of price but does not execute the "
               "order)")
    ( "279-0", "New")
    ( "279-1", "Change")
    ( "279-2", "Delete")
    ( "281-0", "Unknown symbol")
    ( "281-1", "Duplicate MDReqID")
    ( "281-2", "Insufficient Bandwidth")
    ( "281-3", "Insufficient Permissions")
    ( "281-4", "Unsupported SubscriptionRequestType")
    ( "281-5", "Unsupported MarketDepth")
    ( "281-6", "Unsupported MDUpdateType")
    ( "281-7", "Unsupported AggregatedBook")
    ( "281-8", "Unsupported <a href")
    ( "285-0", "Cancelation / Trade Bust")
    ( "285-1", "Error")
    ( "286-0", "Daily Open / Close / Settlement price")
    ( "286-1", "Session Open / Close / Settlement price")
    ( "286-2", "Delivery Settlement price")
    ( "291-1", "Bankrupt")
    ( "292-A", "Ex-Dividend")
    ( "292-B", "Ex-Distribution")
    ( "292-C", "Ex-Rights")
    ( "292-D", "New")
    ( "292-E", "Ex-Interest")
    ( "297-0", "Accepted")
    ( "297-1", "Canceled for Symbol")
    ( "297-2", "Canceled for Security Type(s)")
    ( "297-3", "Canceled for Underlying")
    ( "297-4", "Canceled All")
    ( "297-5", "Rejected")
    ( "303-1", "Manual")
    ( "303-2", "Automatic")
    ( "321-0", "Request Security identity and specifications")
    ( "321-1", "Request Security identity for the specifications provided "
               "(Name of the security is not supplied)")
    ( "321-2", "Request List Security Types")
    ( "321-3", "Request List Securities")
    ( "323-1", "Accept security proposal as is")
    ( "323-2", "Accept security proposal with revisions as indicated in the "
               "message")
    ( "323-3", "List of security types returned per request")
    ( "323-4", "List of securities returned per request")
    ( "323-5", "Reject Security proposal")
    ( "323-6", "Can not match selection criteria")
    ( "325-Y", "Message is being sent unsolicited")
    ( "325-N", "Message is being sent as a result of a prior request")
    ( "326-1", "Opening Delay")
    ( "326-2", "Trading Halt")
    ( "326-3", "Resume")
    ( "326-4", "No Open/No Resume")
    ( "326-5", "Price Indication")
    ( "326-6", "Trading Range Indication")
    ( "326-7", "Market Imbalance Buy")
    ( "326-8", "Market Imbalance Sell")
    ( "326-9", "Market On Close Imbalance Buy")
    ( "326-10", "Market On Close Imbalance Sell")
    ( "326-11", "(not assigned)")
    ( "326-12", "No Market Imbalance")
    ( "326-13", "No Market On Close Imbalance")
    ( "326-14", "ITS Pre-Opening")
    ( "326-15", "New Price Indication")
    ( "326-16", "Trade Dissemination Time")
    ( "326-17", "Ready to trade (start of session)")
    ( "326-18", "Not Available for trading (end of session)")
    ( "326-19", "Not Traded on this Market")
    ( "326-20", "Unknown or Invalid")
    ( "327-I", "Order Imbalance")
    ( "327-X", "Equipment Changeover")
    ( "327-P", "News Pending")
    ( "327-D", "News Dissemination")
    ( "327-E", "Order Influx")
    ( "327-M", "Additional Information")
    ( "328-Y", "Halt was due to common stock being halted")
    ( "328-N", "Halt was not related to a halt of the common stock")
    ( "329-Y", "Halt was due to related security being halted")
    ( "329-N", "Halt was not related to a halt of the related security")
    ( "334-1", "Cancel")
    ( "334-2", "Error")
    ( "334-3", "Correction")
    ( "338-1", "Electronic")
    ( "338-2", "Open Outcry")
    ( "338-3", "Two Party")
    ( "339-1", "Testing")
    ( "339-2", "Simulated")
    ( "339-3", "Production")
    ( "340-1", "Halted")
    ( "340-2", "Open")
    ( "340-3", "Closed")
    ( "340-4", "Pre-Open")
    ( "340-5", "Pre-Close")
    ( "347-ISO-2022-JP", "for using JIS")
    ( "347-EUC-JP", "for using EUC")
    ( "347-Shift_JIS", "for using SJIS")
    ( "347-UTF-8", "for using Unicode")
    ( "368-1", "Unknown symbol (Security)")
    ( "368-2", "Exchange(Security) closed")
    ( "368-3", "Quote exceeds limit")
    ( "368-4", "Too late to enter")
    ( "368-5", "Unknown Quote")
    ( "368-6", "Duplicate Quote")
    ( "368-7", "Invalid bid/ask spread")
    ( "368-8", "Invalid price")
    ( "368-9", "Not authorized to quote security")
    ( "373-0", "Invalid tag number")
    ( "373-1", "Required tag missing")
    ( "373-2", "Tag not defined for this message type")
    ( "373-3", "Undefined Tag")
    ( "373-4", "Tag specified without a value")
    ( "373-5", "Value is incorrect (out of range) for this tag")
    ( "373-6", "Incorrect data format for value")
    ( "373-7", "Decryption problem")
    ( "373-8", "Signature problem")
    ( "373-9", "CompID problem")
    ( "373-10", "SendingTime accuracy problem")
    ( "373-11", "Invalid MsgType")
    ( "374-N", "New")
    ( "374-C", "Cancel")
    ( "377-Y", "Was solcitied")
    ( "377-N", "Was not solicited")
    ( "378-0", "GT Corporate action")
    ( "378-1", "GT renewal / restatement (no corporate action)")
    ( "378-2", "Verbal change")
    ( "378-3", "Repricing of order")
    ( "378-4", "Broker option")
    ( "378-5", "Partial decline of OrderQty (e.g. exchange-initiated partial "
               "cancel)")
    ( "380-0", "Other")
    ( "380-1", "Unkown ID")
    ( "380-2", "Unknown Security")
    ( "380-3", "Unsupported Message Type")
    ( "380-4", "Application not available")
    ( "380-5", "Conditionally Required Field Missing")
    ( "385-S", "Send")
    ( "385-R", "Receive")
    ( "388-0", "Related to displayed price")
    ( "388-1", "Related to market price")
    ( "388-2", "Related to primary price")
    ( "388-3", "Related to local primary price")
    ( "388-4", "Related to midpoint price")
    ( "388-5", "Related to last trade price")
    ( "394-1", "Non Disclosed' Style (e.g. US/European)")
    ( "394-2", "Disclosed' Style (e.g. Japanese)")
    ( "394-3", "No Bidding Process")
    ( "399-1", "Sector")
    ( "399-2", "Country")
    ( "399-3", "Index")
    ( "401-1", "SideValues")
    ( "401-2", "SideValue 2")
    ( "409-1", "5day moving average")
    ( "409-2", "20 day moving average")
    ( "409-3", "Normal Market Size")
    ( "409-4", "Other")
    ( "411-Y", "1")
    ( "411-N", "0")
    ( "414-1", "BuySide explicitly requests status using StatusRequest(Default)"
               "The sell-side firm can however, send a DONE status List Status "
               "Response in an unsolicited fashion")
    ( "414-2", "SellSide periodically sends status using ListStatus. Period "
               "optionally specified in ProgressPeriod")
    ( "414-3", "Real-time execution reports (to be discouraged)")
    ( "416-1", "Net")
    ( "416-2", "Gross")
    ( "418-R", "Risk Trade")
    ( "418-G", "VWAP Guarantee")
    ( "418-A", "Agency")
    ( "418-J", "Guaranteed Close")
    ( "419-2", "Closing Price at morning session")
    ( "419-3", "Closing Price")
    ( "419-4", "Current price")
    ( "419-5", "SQ")
    ( "419-6", "VWAP through a day")
    ( "419-7", "VWAP through a morning session")
    ( "419-8", "VWAP through an afternoon session")
    ( "419-9", "VWAP through a day except YORI")
    ( "419-A", "VWAP through a morning session except YORI")
    ( "419-B", "VWAP through an afternoon session except YORI")
    ( "419-C", "Strike")
    ( "419-D", "Open")
    ( "419-Z", "Others")
    ( "423-1", "Percentage")
    ( "423-2", "per share (e.g. cents per share)")
    ( "423-3", "Fixed Amount (absolute value)")
    ( "427-0", "book out all trades on day of execution")
    ( "427-1", "accumulate executions until order is filled or expires")
    ( "427-2", "accumulate until verbally notified otherwise")
    ( "429-1", "Ack")
    ( "429-2", "Response")
    ( "429-3", "Timed")
    ( "429-4", "ExecStarted")
    ( "429-5", "AllDone")
    ( "429-6", "Alert")
    ( "430-1", "Net")
    ( "430-2", "Gross")
    ( "431-1", "InBiddingProcess")
    ( "431-2", "ReceivedForExecution")
    ( "431-3", "Executing")
    ( "431-4", "Canceling")
    ( "431-5", "Alert")
    ( "431-6", "All Done")
    ( "431-7", "Reject")
    ( "433-1", "Immediate")
    ( "433-2", "Wait for Execute Instruction (e.g. a List Execute message or "
               "phone call before proceeding with execution of the list)")
    ( "434-1", "Order Cancel Request")
    ( "434-2", "Order Cancel/Replace Request")
    ( "5024-1", "Market")
    ( "5024-2", "Limit")
    ( "5024-3", "Stop")
    ( "5024-4", "Stop limit")
    ( "5024-5", "Market on close")
    ( "5024-6", "With or without")
    ( "5024-7", "Limit or better")
    ( "5024-8", "Limit with or without")
    ( "5024-9", "On basis")
    ( "5024-A", "On close")
    ( "5024-B", "Limit on close")
    ( "5024-C", "Forex - Market")
    ( "5024-D", "Previously quoted")
    ( "5024-E", "Previously indicated")
    ( "5024-F", "Forex - Limit")
    ( "5024-G", "Forex - Swap")
    ( "5024-H", "Forex - Previously Quoted")
    ( "5024-I", "Funari (Limit Day Order with unexecuted portion handled as "
                "Market On Close. e.g. Japan)")
    ( "5024-P", "Pegged") ;

  void DismantleFix::dismantle( std::string direction, std::string fixMessage )
  {
    std::cout << std::endl << std::endl << fixMessage ;
    std::cout << std::endl
      <<  "*****************************  "
      << direction
      << "  ***********************************"
      << std::endl;

    std::cout << std::left << std::setw(5)  << "Tag"
      << std::left << std::setw(32) << "Field Name"
      << std::left << std::setw(25) << "Value"
      << "Description"
      << std::endl;

    char charSep[2]; 
    charSep[0] = (char) 1;
    charSep[1] = '\0';

    std::string temp, tag, value, tagVal;

    boost::char_separator<char> sep(charSep);
    boost::char_separator<char> sepEqual("=");

    typedef boost::tokenizer<boost::char_separator<char> > tokenizer;
    tokenizer tokens(fixMessage, sep);
    for ( tokenizer::iterator tok_iter = tokens.begin();
        tok_iter != tokens.end(); ++tok_iter)
    {

      temp.assign(*tok_iter) ;
      tokenizer tokens2( temp, sepEqual) ;
      tokenizer::iterator tok2 = tokens2.begin();

      try 
      {
        tag = *tok2;

        if( ++tok2 == tokens2.end() )
        {
          value = "ERROR - Value Not Assigned" ;
        }
        else
        {
          value = *tok2 ;
        }

        tagVal = tag + "-" + value;
        std::cout << std::left << std::setw(5) << tag 
                  << std::left << std::setw(32) << _fixTags.at(tag) 
                  << std::left << std::setw(25) << value << std::flush; 

        if ( _fixTagsDesc.find(tagVal) != _fixTagsDesc.end() )
          std::cout << _fixTagsDesc.at(tagVal) << std::flush ; 
      }
      catch ( std::exception &e)
      {
        std::cout << "Exception : " << e.what() << std::endl ;
      }
      std::cout << std::endl;
    }

    std::cout << std::endl
      <<  "*****************************  "
      << "END OF " << direction
      << "  *****************************"
      << std::endl;
  }


}

#endif // NDEBUG 
